version: "3.9"

services:
  api:
    container_name: backend_api
    build:
      context: ./compose/development/django/Dockerfile
    ports:
      - "8000:8000"
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    env_file:
      - ./.envs/.development/.django
      - ./.envs/.development/.database
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    env_file:
      - ./.envs/.development/.database
volumes:
  dev-db-data:
